development:
  adapter: postgresql
  encoding: unicode
  database: game_rev_development
  pool: 5
  username: postgres
  password: t7mczoae

test:
  adapter: postgresql
  encoding: unicode
  database: game_rev_test
  pool: 5
  username: postgres
  password: t7mczoae

production:
  adapter: postgresql
  encoding: unicode
  database: game_rev_production
  pool: 5
  username: postgres
  password: t7mczoae
